config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  
  match "about", to: "main#about", via: :get # with HTTP Verb Constraints
  match "hello", to: "main#hello", via: :get
  
  resources :categories do
    member do
      get :delete
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end

  # get 'tasks/index'
  # get 'tasks/show'
  # get 'tasks/new'
  # get 'tasks/edit'
  # get 'tasks/delete'
  # get 'catecogies/index'
  # get 'catecogies/show'
  # get 'catecogies/new'
  # get 'catecogies/edit'
  # get 'catecogies/delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category, :optional => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end

  def destroy
  end
  
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
    @page = params[:page]
    @id = params[:id]
    @created_by = "John Smith"
  end
  
  def hello
    redirect_to(action: "index")
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :task_find_by, only: [:show, :edit, :update, :delete, :destroy]

  def index
    @tasks = Task.order(:position)
  end

  def show
  end

  def new
    @count = Task.count
    @task = Task.new(position: @count +1)
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def delete
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private
  
  def task_find_by
    @task = Task.find_by(id: params[:id])
  end
  

  def task_params
    params.require(:task).permit(
      :name,
      :position,
      :completed,
      :description
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catecogies_helper.rb
module CatecogiesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/delete.html.erb
<h1>Catecogies#delete</h1>
<p>Find me in app/views/catecogies/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Catecogies#edit</h1>
<p>Find me in app/views/catecogies/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Catecogies#index</h1>
<p>Find me in app/views/catecogies/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Catecogies#new</h1>
<p>Find me in app/views/catecogies/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Catecogies#show</h1>
<p>Find me in app/views/catecogies/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/about.html.erb
<%= link_to "Home", {controller: "tasks", action: "index"}%> <br/>
<h1>About</h1>
<%= @created_by%>
<%= @page %>
<%= @id %>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Hello World</p>
<%= link_to "Categories", categories_path %>

<%= link_to "tasks", tasks_path(page: 1) %>

<%= link_to "About", {action: "about", page: 3, id: 10}%> <br/>

app/views/tasks/_form.html.erb
<table>
    <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <td><%= f.label :position %></td>
        <td><%= f.text_field :position %></td>
    </tr>
    <tr>
        <td><%= f.label :completed %></td>
        <td><%= f.check_box :completed %></td>
    </tr>
    <tr>
        <td><%= f.label :description %></td>
        <td><%= f.text_area :description %></td>
    </tr>
</table>

app/views/tasks/delete.html.erb
<%= link_to "Back to List", tasks_path, class: "back-link" %>

<div class="tasks delete">
    <h2>Delete Task</h2>

    <%= form_for @task, method: "delete" do |f| %>
        <p> Are u wanna delete task</p>
        <p><%= @task.name %></p>

        <div class="form-button">
            <%= f.submit "Delete task"%>
        </div>
    <% end%>
</div>

app/views/tasks/edit.html.erb
<%= link_to "Back to list", tasks_path, class: "back-list" %>
<div class="back edit">
    <h2>Edit task</h2>

    <%= form_for @task do |f| %>
        <%= render partial: 'form', locals: {f: f} %>
        <div class="form=-buttons">
            <%= f.submit "Edit task" %>
        </div>
    <% end %>
</div>

app/views/tasks/index.html.erb
<%= link_to("Back to Homepage", root_path) %><br />

<div class="tasks index">
    <h2>Tasks</h2>

    <%= link_to("Add New Task", new_task_path ,class: 'action new') %>

    <table class="listing" sumsary="Task list" style="width: 100%; text-align: center;">
        <tr ckass="header">
            <th>#</th>
            <th>Task</th>
            <th>Comp1eted</th>
            <th>Category</th>
            <th>Actions</th>
        </tr>
        <% @tasks.each do |task| %>
        <tr>
            <td><%= task.position %></td>
            <td><%= task.name %></td>
            <td><%= task.completed? ? 'Yes' : 'No' %></td>
            <td><%= task.category&.name || '=' %></td>
            <td class="actions">
                <%= link_to("Show", task_path(task) ,class: 'action show') %>
                <%= link_to("Edit", edit_task_path(task) ,class: 'action edit') %>
                <%= link_to("Delete", delete_task_path(task), class: 'action delete') %>
            </td>
        </tr>
        <% end %>
    </table>
</div>

app/views/tasks/new.html.erb
<%= link_to "Back to list", tasks_path, class: "back-list" %>
<div class="back new">
    <h2>Create task</h2>

    <%= form_for @task do |f| %>
        <%= render partial: 'form', locals: {f: f}%>
        <div class="form=-buttons">
            <%= f.submit "Create task" %>
        </div>
    <% end %>
</div>

app/views/tasks/show.html.erb
<%= link_to 'Back to list', tasks_path, class: "black-link"%>

<div class="tasks show">
    <h2>Show Task</h2>

    <div class="actions">
        <%= link_to 'Edit', edit_task_path(@task)%>
        <%= link_to 'Delete', delete_task_path(@task)%>
    </div>

    <table summary="Task detail view">
        <tr>
            <th>Name</th>
            <td><%= @task.name %></td>
        </tr>
        <tr>
            <th>Postision</th>
            <td><%= @task.position %></td>
        </tr>
        <tr>
            <th>Completed</th>
            <td><%= @task.completed? ? 'Yes' : 'No' %></td>
        </tr>
        <tr>
            <th>Description</th>
            <td><%= @task.description %></td>
        </tr>
        <tr>
            <th>Category</th>
            <td><%= @task.category&.name || "=" %></td>
        </tr>
        <tr>
            <th>Created</th>
            <td><%= @task.created_at %></td>
        </tr>
        <tr>
            <th>Updated</th>
            <td><%= @task.updated_at %></td>
        </tr>
    </table>
</div>